### ISSUE TITLE
Replace OB-1 install with concat install

### ISSUE THREAD

**Issue by parkan** [mediachain/deploy#2]
Replace install flow here https://github.com/mediachain/deploy/blob/15423cc7ae3f3789712432e64ef7d03c01c3ef66/src/install.sh

with concat

I'm a little confused by their usage/non-usage of Docker?

**Comment by denisnazarov** [comment]
I'd be down to spend an hour or two hacking on this Friday!

**Comment by parkan** [comment]
This is something that @yusefnapora can probably crush pretty effectively (yusef, are you seeing these notifications?)
