### ISSUE TITLE
Change google analytics token, digital ocean referral code

### ISSUE THREAD

**Issue by yusefnapora** [mediachain/deploy#5]
These still point to blockstack; let's change them so we can know if people are using it and get a little referral credit.

**Comment by parkan** [comment]
Here's a referral link for us, I'm assuming the code is the thing at the end: https://m.do.co/c/a688ee6191f9

**Comment by yusefnapora** [comment]
sweet, I updated this and deployed to github pages.

**Comment by yusefnapora** [comment]
It looks like I already ripped out the old googl analytics token btw.  We can add our own back if needed
